# ----------------------------------------------------------------------
# |
# |  event_periodic.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-12-08 12:18:14
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on periodic"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  schedule:
    - cron: '0 0 * * *' # Once a day at 12am UTC

jobs:
  _638cc6ec-f116-488b-bf59-dd85e1109570:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-Common_SimpleSchema/.github/workflows/validate.yaml@CI-latest
    with:
      repo_branch: ${{ github.ref_name }}

  _eafa48a4-6e18-49a5-bd4a-b43f50aec2b2:
    name: "Validate with Dependencies (${{ github.ref_name }})"
    uses: davidbrownell/v4-Common_SimpleSchema/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch: ${{ github.ref_name }}

    needs:
      - _638cc6ec-f116-488b-bf59-dd85e1109570
