# ----------------------------------------------------------------------
# |
# |  event_on_push.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-12-08 12:18:05
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on push"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - main

concurrency: "on_push-${{ github.ref_name }}"

jobs:
  _017861b0-3739-4b70-a391-37c97e7d5147:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-Common_SimpleSchema/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch: ${{ github.ref_name }}

  _1b24e7b5-d1aa-4291-8ac5-75f8ed7378d9:
    name: "Promote"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_promote.yaml@CI-v1

    needs:
      - _017861b0-3739-4b70-a391-37c97e7d5147
