# ----------------------------------------------------------------------
# |
# |  manual_validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-12-08 12:18:31
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "Validate"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  _fc3d4c19-5b8c-46b4-bb52-df2cf38e7265:
    name: "Validate"
    uses: davidbrownell/v4-Common_SimpleSchema/.github/workflows/validate.yaml@CI-latest
    with:
      repo_branch:                          ${{ github.ref_name }}
