# ----------------------------------------------------------------------
# |
# |  validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-12-08 12:18:53
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[callable] Validates Common_SimpleSchema"

on:
  workflow_call:
    inputs:
      repo_branch:                          {type: string, required: true}
      force_setup:                          {type: boolean, required: false, default: false}
      force_activate:                       {type: boolean, required: false, default: false}
      no_cache:                             {type: boolean, required: false, default: false}

      bootstrap_branch_overrides:           {type: string, required: false}

jobs:
  _ab16798c-e933-4346-a1ce-bddefbf34767:
    name: "Build and Test: dev"

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_validate.yaml@CI-v1
    with:
      job_name_prefix: "Common_SimpleSchema"
      repo_name: davidbrownell/v4-Common_SimpleSchema
      repo_branch: ${{ inputs.repo_branch }}
      bootstrap_branch_overrides: ${{ inputs.bootstrap_branch_overrides }}

      os: ${{ matrix.os }}
      configuration: dev

      run_PylintVerifier: true
      run_Builder: true
      run_MatchTests: false                 # TODO: true

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests: 0                  # TODO: 3
      execute_FunctionalTests: 0            # TODO: 1
      execute_IntegrationTests: 0           # TODO: 1
      execute_SystemTests: 0                # TODO: 1
      execute_LocalEndToEndTests: 0         # TODO: 1
      execute_EndToEndTests: 0
      execute_BuildVerificationTests: 0
      execute_PerformanceTests: 0

  _f421350c-8fed-4c2d-be38-535c38ef59d1:
    name: "Build and Test: standard"

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate.yaml@CI-v1
    with:
      job_name_prefix: "Common_SimpleSchema"
      repo_name: davidbrownell/v4-Common_SimpleSchema
      repo_branch: ${{ inputs.repo_branch }}
      bootstrap_branch_overrides: ${{ inputs.bootstrap_branch_overrides }}

      os: ${{ matrix.os }}
      configuration: standard

      run_Builder: true
      run_MatchTests: false                 # TODO: true

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests: 0                  # TODO: 3
      execute_FunctionalTests: 0            # TODO: 1
      execute_IntegrationTests: 0           # TODO: 1
      execute_SystemTests: 0                # TODO: 1
      execute_LocalEndToEndTests: 0         # TODO: 1
      execute_EndToEndTests: 0
      execute_BuildVerificationTests: 0
      execute_PerformanceTests: 0
