# ----------------------------------------------------------------------
# |
# |  validate_with_dependencies.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-12-08 12:18:46
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[callable] Validates Common_SimpleSchema (and its dependencies)"

on:
  workflow_call:
    inputs:
      repo_branch:                          {type: string, required: true}

jobs:
  _de8c051b-c184-40df-b9bd-41245aee1267:
    name: "Common_SimpleSchema"
    uses: davidbrownell/v4-Common_SimpleSchema/.github/workflows/validate.yaml@CI-ExperimentalCache # TODO: CI-latest
    with:
      repo_branch: ${{ inputs.repo_branch }}
      bootstrap_branch_overrides: "Common_SimpleSchema:${{ inputs.repo_branch }}"
