# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/validate.jinja2.yaml
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-12-08 12:18:53
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[callable] Validates Common_SimpleSchema"

on:
  workflow_call:
    inputs:
      repo_branch:                          {type: string, required: true}
      force_setup:                          {type: boolean, required: false, default: false}
      force_activate:                       {type: boolean, required: false, default: false}
      no_cache:                             {type: boolean, required: false, default: false}

      bootstrap_branch_overrides:           {type: string, required: false}

jobs:
  # ----------------------------------------------------------------------
  _2138a5e2-b9e6-45c7-8220-4138c4880ff8:
    name: "Build and Test: standard"

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate.yaml@CI-v1
    with:
      job_name_prefix: "Common_SimpleSchema"
      repo_name: davidbrownell/v4-Common_SimpleSchema
      repo_branch: ${{ inputs.repo_branch }}
      bootstrap_branch_overrides: ${{ inputs.bootstrap_branch_overrides }}

      os: ${{ matrix.os }}
      configuration: standard

      run_Builder: true
      run_MatchTests: true

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests: 3
      execute_FunctionalTests: 1
      execute_IntegrationTests: 1
      execute_SystemTests: 1
      execute_LocalEndToEndTests: 1
      execute_EndToEndTests: 0
      execute_BuildVerificationTests: 1
      execute_PerformanceTests: 0

# Note that we aren't using a matrix for the os here as we want to increase overall throughput
# (rather than forcing the binary validation job to wait until all of the dev jobs are complete).
  # ----------------------------------------------------------------------
  # |
  # |  macos-latest
  # |
  # ----------------------------------------------------------------------
  _61804fa1-d9d9-47bc-890f-838f95197a1d:
    name: "Build and Test: dev"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_validate.yaml@CI-v1
    with:
      job_name_prefix: "Common_SimpleSchema"
      repo_name: davidbrownell/v4-Common_SimpleSchema
      repo_branch: ${{ inputs.repo_branch }}
      bootstrap_branch_overrides: ${{ inputs.bootstrap_branch_overrides }}

      os: macos-latest
      configuration: dev

      run_PylintVerifier: true
      run_Builder: true
      run_MatchTests: true

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests: 3
      execute_FunctionalTests: 1
      execute_IntegrationTests: 1
      execute_SystemTests: 1
      execute_LocalEndToEndTests: 1
      execute_EndToEndTests: 1
      execute_BuildVerificationTests: 1
      execute_PerformanceTests: 0

  # ----------------------------------------------------------------------
  _8e299ffe-70f8-487b-abea-831c1df63323:
    name: "Common_SimpleSchema (macos-latest, dev binaries)"
    runs-on: macos-latest
    needs:
      - _61804fa1-d9d9-47bc-890f-838f95197a1d

    steps:
      - name: "[Impl] Dump Contexts"
        if: ${{ startsWith('macos-latest', 'ubuntu') }}
        uses: davidbrownell/v4-Common_Foundation/.github/actions/dump_contexts@CI-v1

      # outputs:
      #   - github_workspace
      #   - local_script_prefix
      #   - script_extension
      #   - shell_name
      #   - source_command
      #   - sudo_command
      #
      - name: "[Impl] Initialize OS-Specific Variables"
        id: initialize
        uses: davidbrownell/v4-Common_Foundation/.github/actions/initialize@CI-v1
        with:
          os: macos-latest

      # outputs:
      #   - archive_prefix
      #   - repo_dir
      #   - repo_dependencies_dir
      #
      - name: Checkout Source
        id: checkout_source
        uses: davidbrownell/v4-Common_Foundation/.github/actions/checkout_source@CI-v1
        with:
          repo_name: davidbrownell/v4-Common_SimpleSchema
          repo_branch: ${{ inputs.repo_branch }}

          os: macos-latest
          configuration: dev

          shell_name: ${{ steps.initialize.outputs.shell_name }}

      # outputs:
      #   - artifacts_dir
      #
      - name: Unbundle Build Artifacts
        id: unbundle
        uses: davidbrownell/v4-Common_Foundation/.github/actions/unbundle_builder_artifacts@CI-v1
        with:
          archive_prefix: ${{ steps.checkout_source.outputs.archive_prefix }}
          artifacts_path: src/SimpleSchema/Build

          os: macos-latest

          shell_name: ${{ steps.initialize.outputs.shell_name }}
          working_dir: ${{ steps.initialize.outputs.github_workspace }}/artifacts

      - name: Run Test
        run: |
          python3 "${{ steps.checkout_source.outputs.repo_dir }}/src/SimpleSchema/src/SimpleSchema/TestFiles/Binary_BuildVerificationTest.py" "${{ steps.unbundle.outputs.artifacts_dir }}"

  # ----------------------------------------------------------------------
  # |
  # |  ubuntu-latest
  # |
  # ----------------------------------------------------------------------
  _7a76a3ae-1aab-4649-ba80-00b7f6b4f5cf:
    name: "Build and Test: dev"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_validate.yaml@CI-v1
    with:
      job_name_prefix: "Common_SimpleSchema"
      repo_name: davidbrownell/v4-Common_SimpleSchema
      repo_branch: ${{ inputs.repo_branch }}
      bootstrap_branch_overrides: ${{ inputs.bootstrap_branch_overrides }}

      os: ubuntu-latest
      configuration: dev

      run_PylintVerifier: true
      run_Builder: true
      run_MatchTests: true

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests: 3
      execute_FunctionalTests: 1
      execute_IntegrationTests: 1
      execute_SystemTests: 1
      execute_LocalEndToEndTests: 1
      execute_EndToEndTests: 1
      execute_BuildVerificationTests: 1
      execute_PerformanceTests: 0

  # ----------------------------------------------------------------------
  _d466fdd6-88d0-4b5c-b108-d310d471a2d0:
    name: "Common_SimpleSchema (ubuntu-latest, dev binaries)"
    runs-on: ubuntu-latest
    needs:
      - _7a76a3ae-1aab-4649-ba80-00b7f6b4f5cf

    steps:
      - name: "[Impl] Dump Contexts"
        if: ${{ startsWith('ubuntu-latest', 'ubuntu') }}
        uses: davidbrownell/v4-Common_Foundation/.github/actions/dump_contexts@CI-v1

      # outputs:
      #   - github_workspace
      #   - local_script_prefix
      #   - script_extension
      #   - shell_name
      #   - source_command
      #   - sudo_command
      #
      - name: "[Impl] Initialize OS-Specific Variables"
        id: initialize
        uses: davidbrownell/v4-Common_Foundation/.github/actions/initialize@CI-v1
        with:
          os: ubuntu-latest

      # outputs:
      #   - archive_prefix
      #   - repo_dir
      #   - repo_dependencies_dir
      #
      - name: Checkout Source
        id: checkout_source
        uses: davidbrownell/v4-Common_Foundation/.github/actions/checkout_source@CI-v1
        with:
          repo_name: davidbrownell/v4-Common_SimpleSchema
          repo_branch: ${{ inputs.repo_branch }}

          os: ubuntu-latest
          configuration: dev

          shell_name: ${{ steps.initialize.outputs.shell_name }}

      # outputs:
      #   - artifacts_dir
      #
      - name: Unbundle Build Artifacts
        id: unbundle
        uses: davidbrownell/v4-Common_Foundation/.github/actions/unbundle_builder_artifacts@CI-v1
        with:
          archive_prefix: ${{ steps.checkout_source.outputs.archive_prefix }}
          artifacts_path: src/SimpleSchema/Build

          os: ubuntu-latest

          shell_name: ${{ steps.initialize.outputs.shell_name }}
          working_dir: ${{ steps.initialize.outputs.github_workspace }}/artifacts

      - name: Run Test
        run: |
          python3 "${{ steps.checkout_source.outputs.repo_dir }}/src/SimpleSchema/src/SimpleSchema/TestFiles/Binary_BuildVerificationTest.py" "${{ steps.unbundle.outputs.artifacts_dir }}"

  # ----------------------------------------------------------------------
  # |
  # |  windows-latest
  # |
  # ----------------------------------------------------------------------
  _bbf0a875-46b3-463a-b037-5ac1f70bfdd7:
    name: "Build and Test: dev"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_validate.yaml@CI-v1
    with:
      job_name_prefix: "Common_SimpleSchema"
      repo_name: davidbrownell/v4-Common_SimpleSchema
      repo_branch: ${{ inputs.repo_branch }}
      bootstrap_branch_overrides: ${{ inputs.bootstrap_branch_overrides }}

      os: windows-latest
      configuration: dev

      run_PylintVerifier: true
      run_Builder: true
      run_MatchTests: true

      force_setup: ${{ inputs.force_setup }}
      force_activate: ${{ inputs.force_activate }}
      no_cache: ${{ inputs.no_cache }}

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests: 3
      execute_FunctionalTests: 1
      execute_IntegrationTests: 1
      execute_SystemTests: 1
      execute_LocalEndToEndTests: 1
      execute_EndToEndTests: 1
      execute_BuildVerificationTests: 1
      execute_PerformanceTests: 0

  # ----------------------------------------------------------------------
  _dd98a57e-ea99-4b01-bae5-6c637e70402d:
    name: "Common_SimpleSchema (windows-latest, dev binaries)"
    runs-on: windows-latest
    needs:
      - _bbf0a875-46b3-463a-b037-5ac1f70bfdd7

    steps:
      - name: "[Impl] Dump Contexts"
        if: ${{ startsWith('windows-latest', 'ubuntu') }}
        uses: davidbrownell/v4-Common_Foundation/.github/actions/dump_contexts@CI-v1

      # outputs:
      #   - github_workspace
      #   - local_script_prefix
      #   - script_extension
      #   - shell_name
      #   - source_command
      #   - sudo_command
      #
      - name: "[Impl] Initialize OS-Specific Variables"
        id: initialize
        uses: davidbrownell/v4-Common_Foundation/.github/actions/initialize@CI-v1
        with:
          os: windows-latest

      # outputs:
      #   - archive_prefix
      #   - repo_dir
      #   - repo_dependencies_dir
      #
      - name: Checkout Source
        id: checkout_source
        uses: davidbrownell/v4-Common_Foundation/.github/actions/checkout_source@CI-v1
        with:
          repo_name: davidbrownell/v4-Common_SimpleSchema
          repo_branch: ${{ inputs.repo_branch }}

          os: windows-latest
          configuration: dev

          shell_name: ${{ steps.initialize.outputs.shell_name }}

      # outputs:
      #   - artifacts_dir
      #
      - name: Unbundle Build Artifacts
        id: unbundle
        uses: davidbrownell/v4-Common_Foundation/.github/actions/unbundle_builder_artifacts@CI-v1
        with:
          archive_prefix: ${{ steps.checkout_source.outputs.archive_prefix }}
          artifacts_path: src/SimpleSchema/Build

          os: windows-latest

          shell_name: ${{ steps.initialize.outputs.shell_name }}
          working_dir: ${{ steps.initialize.outputs.github_workspace }}/artifacts

      - name: Run Test
        run: |
          python3 "${{ steps.checkout_source.outputs.repo_dir }}/src/SimpleSchema/src/SimpleSchema/TestFiles/Binary_BuildVerificationTest.py" "${{ steps.unbundle.outputs.artifacts_dir }}"
